### ISSUE TITLE
Inverted Y stick

### ISSUE THREAD

**Issue by DirtyDan123** [vrcsix/nintendont#1]
Playing 20XX and every button works fine except the Y stick which is inverted.  I have looked all over the internet for solutions like using an HID Test, but the official Nintendo adapter I am using isn't working.

**Comment by vrcsix** [comment]
Hello @DirtyDan123! This is just a personal Git mirror that was set up before Nintendont moved to GitHub. I see you've open an issue with the official project, so I'm going to close this.
